### ISSUE TITLE
hardcoded variant column name

### ISSUE THREAD

**Issue by websitelytics** [shyaginuma/casual_inference#48]
https://github.com/shyaginuma/casual_inference/blob/f0db3b34a9ad705ad0a319feb1f83afcc6624c71/casual_inference/evaluator/abtest.py#L210-L223

It seems that in the `_diagnose_srm` variant column name is hardcoded.

**Comment by shyaginuma** [comment]
Thanks for raising the issue!
Fixed in #49 , let me close this issue.
